apiVersion: v1
kind: Service
metadata:
  name: techchallenge-backend-service
spec:
  type: NodePort
  selector:
    app: techchallenge-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000