apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: techchallenge-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: localstorage