apiVersion: v1
kind: PersistentVolume
metadata:
  name: techchallenge-database-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: localstorage
  hostPath:
    path: /tmp