apiVersion: v1
kind: Service
metadata:
  name: techchallenge-database-service
spec:
  type: NodePort
  selector:
    app: techchallenge-database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 32000